### ISSUE TITLE
Section headers stand out better

### ISSUE THREAD

**Issue by YOYOK9** [CurseForgeCommunity/cf-troubleshooter-win#2]
Currently the sections are all the same text size, making it harder for some users to see the section changes (specially if English isnt 1st language)

Maybe a bold underline or just a bigger font?

**Comment by itssimple** [comment]
![image](https://user-images.githubusercontent.com/11502257/218252386-56eed704-0aa0-4aa9-a46a-17c8d5d788cb.png)
Something like this will be the result for now, until I figure out a better way to do it. ^^

**Comment by itssimple** [comment]
Fixed in v1.1.0!
